version: '2'

services:
  rust:
    image: flieske/gramine-rust:latest
    container_name: "rust-sgx"
    build:
      context: .
      args:
        - projectName=hello_world
        - webFiles=web_files
    devices:
      - "/dev/sgx_enclave:/dev/sgx_enclave"
    stdin_open: true              # docker run -i
    tty: true                     # docker run -t
  rust-nosgx:
    image: flieske/gramine-rust:latest
    container_name: "rust-nosgx"
    build:
      context: .
      args:
        - projectName=hello_world
        - webFiles=web_files
    devices:
      - "/dev/sgx_enclave:/dev/sgx_enclave"
    stdin_open: true              # docker run -i
    tty: true                     # docker run -t
    entrypoint: "/entrypoint/app"
